# Nom logique de l'application
spring.application.name=Altaris

# URL JDBC de la base MySQL
spring.datasource.url=${DATABASE_URL}

# Identifiants de connexion \u00E0 la base
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

# Classe du driver JDBC MySQL
spring.datasource.driver-class-name=${DATABASE_DRIVER_CLASS_NAME}

# Strat\u00E9gie de nommage Hibernate :
# conserve exactement les noms des entit\u00E9s/annotations
# (ne convertit pas en minuscules ni n'ajoute d'underscores)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Cr\u00E9e les tables si elles n'existent pas et les supprime quand l'app est arr\u00EAt\u00E9e
#spring.jpa.hibernate.ddl-auto=create-drop

# Met \u00E0 jour les tables si elles existent d\u00E9j\u00E0, et les cr\u00E9e sinon. Les tables ne sont pas supprim\u00E9es quand l'app est arr\u00EAt\u00E9e
spring.jpa.hibernate.ddl-auto=update

# Contexte de l'application : pr\u00E9fixe toutes les routes REST par /api
server.servlet.context-path=/api

# Configuration Mail Hog SMTP pour le dev
spring.mail.host=localhost
spring.mail.port=1025